# Generated by Django 3.1.7 on 2021-03-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210317_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='engineering', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateposted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
